name: JS Test
on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: latest
      - uses: actions/setup-node@v3
        with:
          # registry-url: "https://registry.npmjs.org"
          node-version: 16
          cache: pnpm
      - name: install dependencies
        run: pnpm install --frozen-lockfile
      - name: run test
        run: pnpm test:cov
      - uses: codecov/codecov-action@v2
      - name: test build
        run: pnpm build
