name: Ship js Manual Prepare
on:
  workflow_dispatch:
    inputs:
      version:
        description: The semver-compliant version to tag the release with, e.g. 1.2.3, 1.0.0-rc.1
        required: false
        default: '*'

jobs:
  manual_prepare:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: master
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
      - run: npx shipjs prepare --yes --no-browse
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_INCOMING_HOOK: ${{ secrets.SLACK_INCOMING_HOOK }}
          FORCE_NEXT_VERSION: ${{ github.event.inputs.version }}
